# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f5f4b7a166c4c9db3b7302bb5bb9ea5cf92dada24cffb1b869f7e86419256a58da55a47e2a0e700bacf480b063151a7caab80788276a8e97bca48875c1b09b6

test:
  secret_key_base: 39acd5837a989f61e03b1f7c68f94341540d3d4a351da4c3d0e6e50adc21885333ec2bbf0ff27aa556c5537b7565c62f072027ec5c8c58d03a58fecebb0b061d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
